# Generated by Django 4.2 on 2023-04-28 19:48

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(verbose_name='Collection Time')),
                ('filename', models.CharField(db_index=True, max_length=128, verbose_name='Filename')),
                ('file', models.FileField(upload_to=app.models._collections_directory_path)),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
    ]
