# Generated by Django 4.2 on 2023-04-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collected_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Collection Time'),
        ),
    ]
